import { type ModuleOptions, type IModuleInstance } from '../contracts/ModuleContract.js';
export declare class ModuleOscilloscope implements IModuleInstance {
    private el;
    private content;
    private canvas;
    private ctx;
    private options;
    private isPowered;
    private sourceA;
    private sourceB;
    private isDual;
    private isFrozen;
    private syncEnabled;
    private timebase;
    private dataA;
    private dataB;
    private allSources;
    private filteredSources;
    private pollingInterval;
    private animationId;
    private resizeObserver;
    private modalActive;
    private modalCanvas;
    private modalCtx;
    private modalTimebase;
    constructor(el: HTMLElement, content: HTMLElement, options: ModuleOptions);
    init(): Promise<void>;
    private generateGroupedOptions;
    private setupResizeObserver;
    private fetchSourcesWithRetry;
    private render;
    private updateSelectors;
    private bindEvents;
    private bindModalEvents;
    private openModal;
    private syncModalInputs;
    private startPolling;
    private startDrawLoop;
    private resize;
    private draw;
    private renderTrace;
    onStateUpdate(state: any): void;
    destroy(): void;
}
export default ModuleOscilloscope;
//# sourceMappingURL=ModuleOscilloscope.d.ts.map